# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Leo von Kleist
tagline:          Blog
description:      CS Student @ ETH Zurich
url:              http://hyde.getpoole.com
baseurl:          /
github_username: leokleist
linkedin_username: leonard-von-kleist-428323102


paginate:         5

# Custom vars
version:          2.1.0


